class_reference:
    path: /{version}/class-reference
    defaults:
        _controller: 'Bolt\Docs\Controller\Site:getClassReference'
    requirements:
        version: '(\d+\.(\d+|x)|master)'
cheatsheet:
    path: /{version}/cheatsheet
    defaults:
        _controller: 'Bolt\Docs\Controller\Site:getCheatsheet'
    requirements:
        version: '(\d+\.(\d+|x)|master)'

page:
    path: /{version}/{page}
    defaults:
        _controller: 'Bolt\Docs\Controller\Site:getPage'
        version: ''
        page: ''
    requirements:
        version: '(\d+\.(\d+|x)|master)'
        page: '.*'

sitemap:
    path: /sitemap/{version}.xml
    defaults:
        _controller: 'Bolt\Docs\Controller\Site:getSitemap'
    requirements:
        version: '(\d+\.(\d+|x)|master)'
sitemap_list:
    path: /sitemap.xml
    defaults:
        _controller: 'Bolt\Docs\Controller\Site:getSitemapList'

# Responsible for handling the redirect of canonical routes to the current version
canonical_redirect:
    path: /{page}
    controller: 'Bolt\Docs\Controller\Site:getPage'
    requirements:
        page: '.*'
    defaults:
        permanent: true
